-- Initial SQL migration script to create the database tables
CREATE TABLE inventory (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(100),
    quantity NUMBER,
    price NUMBER,
    batch_name VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE employees (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    contact_details VARCHAR2(255),
    department VARCHAR2(100),
    joined_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sales (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(100),
    quantity NUMBER,
    sale_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
